server:
  port: 0
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:h2:mem:auth
    username: petrov
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
